#!/usr/bin/env python3
"""
Phase 3b, validate + emit. Takes the blind author's proposed invariants, and deterministically:
  - dedups across the author passes (by id / by structural equality),
  - checks every referenced node id exists in the graph,
  - checks each rule expression compiles (safe eval over the node vocabulary),
  - verifies each invariant's `quote` verbatim against the scenario (verify_quotes),
  - flags correlation invariants for extra human scrutiny (the consumption trap).
Writes the VALID invariants to invariants.yaml (the file mc_face_validity reads) + an invariants_report
listing every proposal with pass/fail + quotes, for the one-time human ratification.

Nothing here trusts the author on say-so: an invariant that references a bad node, won't compile, or
carries an unverifiable quote is dropped and reported, not shipped.

Usage:
  python3 validate_invariants.py --proposals AUTHOR_OUTPUT --graph GRAPH.json --scenario SCEN.md \
      --out-dir OUTDIR
Writes OUTDIR/invariants.yaml + OUTDIR/invariants_report.json
"""
import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify_quotes import load_scenario, verify_quote

REQUIRED = {"coupling": ["when", "then"], "pointwise": ["rule"], "correlation": ["a", "b", "expect"]}


def unwrap(doc):
    r = doc.get("result", doc) if isinstance(doc, dict) else {}
    passes = r.get("passes", [])
    invs = []
    for p in passes:
        invs.extend(p.get("invariants", []) or [])
    return invs


def refs(inv, all_ids):
    text = " ".join(str(inv.get(k) or "") for k in ("when", "then", "rule", "a", "b"))
    return [nid for nid in all_ids if re.search(r"\b" + re.escape(nid) + r"\b", text)]


def expr_ok(e, all_ids):
    if not e:
        return True
    try:
        code = compile(e, "<inv>", "eval")
    except Exception:
        return False
    return all((n in all_ids or n in ("and", "or", "not", "True", "False")) for n in code.co_names)


def validate(inv, all_ids, scen_norm):
    problems = []
    kind = inv.get("kind")
    if kind not in REQUIRED:
        return ["unknown kind"]
    for f in REQUIRED[kind]:
        if not inv.get(f):
            problems.append(f"missing {f}")
    used = refs(inv, all_ids)
    # detect referenced-looking tokens that are not real ids
    text = " ".join(str(inv.get(k) or "") for k in ("when", "then", "rule"))
    for tok in re.findall(r"[a-z_][a-z0-9_]{3,}", text):
        if tok not in all_ids and tok not in ("and", "or", "not", "true", "false"):
            problems.append(f"unknown node id '{tok}'")
    if not used and kind != "correlation":
        problems.append("references no known node")
    for f in ("when", "then", "rule"):
        if inv.get(f) and not expr_ok(inv[f], all_ids):
            problems.append(f"{f} does not compile")
    if kind == "correlation":
        for f in ("a", "b"):
            if inv.get(f) and inv[f] not in all_ids:
                problems.append(f"{f}='{inv.get(f)}' not a node")
    if not verify_quote(inv.get("quote", ""), scen_norm):
        problems.append("quote not verbatim in scenario")
    return problems


def to_yaml(invs):
    lines = ["# Auto-authored plausibility invariants (blind to graph edges), quote-grounded and",
             "# deterministically validated. Human-ratify before trusting. Generated by Phase 3b.", "",
             "invariants:"]
    for v in invs:
        lines.append(f"  - id: {v['id']}")
        lines.append(f"    kind: {v['kind']}")
        for f in ("when", "then", "rule", "a", "b"):
            if v.get(f):
                lines.append(f"    {f}: {json.dumps(v[f])}")
        if v.get("within_rounds") is not None:
            lines.append(f"    within_rounds: {int(v['within_rounds'])}")
        if v.get("expect"):
            lines.append(f"    expect: {json.dumps(v['expect'])}")
        mvr = v.get("max_violation_rate")
        lines.append(f"    max_violation_rate: {mvr if mvr is not None else 0.2}")
        lines.append(f"    quote: {json.dumps(v.get('quote',''))}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--proposals", required=True)
    ap.add_argument("--graph", required=True)
    ap.add_argument("--scenario", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    all_ids = [n["id"] for n in json.load(open(args.graph))["nodes"]]
    scen_norm = load_scenario(args.scenario)
    proposals = unwrap(json.load(open(args.proposals)))

    seen_ids, seen_sig, report, valid = set(), set(), [], []
    for inv in proposals:
        # dedup across author passes by id AND by semantic signature (kind + the node pair a rule
        # couples), so pass-1/pass-2 restatements of the same expectation collapse to one.
        when_refs = tuple(sorted(refs({"when": inv.get("when"), "rule": inv.get("rule")}, all_ids)))
        then_refs = tuple(sorted(refs({"then": inv.get("then")}, all_ids)))
        sig = (inv.get("kind"), when_refs, then_refs, inv.get("a"), inv.get("b"))
        dup = inv.get("id") in seen_ids or sig in seen_sig
        seen_ids.add(inv.get("id"))
        seen_sig.add(sig)
        problems = validate(inv, all_ids, scen_norm)
        rec = {"id": inv.get("id"), "kind": inv.get("kind"), "duplicate": dup,
               "valid": (not problems and not dup), "problems": problems,
               "correlation_scrutiny": inv.get("kind") == "correlation",
               "quote": inv.get("quote"), "rationale": inv.get("rationale")}
        report.append(rec)
        if rec["valid"]:
            valid.append(inv)

    os.makedirs(args.out_dir, exist_ok=True)
    open(os.path.join(args.out_dir, "invariants.yaml"), "w").write(to_yaml(valid))
    json.dump({"n_proposed": len(proposals), "n_valid": len(valid),
               "n_correlations_flagged": sum(1 for r in report if r["correlation_scrutiny"] and r["valid"]),
               "report": report},
              open(os.path.join(args.out_dir, "invariants_report.json"), "w"), indent=2)

    print(f"invariant authoring: {len(proposals)} proposed -> {len(valid)} valid "
          f"(after quote-verification, node-check, compile-check, dedup)")
    for r in report:
        mark = "OK " if r["valid"] else "DROP"
        extra = " [correlation: human-scrutinize]" if (r["correlation_scrutiny"] and r["valid"]) else ""
        print(f"  {mark} {r['kind']:11} {r['id']:28}{extra}"
              + ("" if r["valid"] else f"  -- {'; '.join(r['problems']) or 'duplicate'}"))
    print(f"\nwrote {args.out_dir}/invariants.yaml (+ invariants_report.json for human ratification)")
    print("HUMAN: ratify the rule set once — especially any correlation flagged above.")


if __name__ == "__main__":
    main()
